CREATE TABLE "ANNO_AGGREGAZIONE_PER_STIPENDIO_MEDIO_ORARIO" ( "ID_ANNO" INTEGER (3) PRIMARY KEY ,"ANNO" INTEGER (4)); 
CREATE TABLE "ANNO_AGGREGAZIONE_PER_STIPENDIO_MEDIO_MENSILE" ( "ID_ANNO" INTEGER (3) PRIMARY KEY ,"ANNO" INTEGER (4)); 
CREATE TABLE "ANNO_AGGREGAZIONE_PER_STIPENDIO_ANNUO" ( "ID_ANNO" INTEGER (3) PRIMARY KEY ,"ANNO" INTEGER (4)); 
CREATE TABLE "LIVELLO_AGGREGAZIONE_PER_LIVELLO" ( "ID_LIVELLO" INTEGER (3) PRIMARY KEY ,"GRADO" INTEGER (3)); 
CREATE TABLE "MATRICOLA_AGGREGAZIONE_PER_STIPENDIO_MEDIO_ORARIO" ( "MATRICOLA" INTEGER (3) PRIMARY KEY ); 
CREATE TABLE "MATRICOLA_AGGREGAZIONE_PER_STIPENDIO_MEDIO_MENSILE" ( "MATRICOLA" INTEGER (3) PRIMARY KEY ); 
CREATE TABLE "MATRICOLA_AGGREGAZIONE_PER_STIPENDIO_ANNUO" ( "MATRICOLA" INTEGER (3) PRIMARY KEY ); 
CREATE TABLE "NOME_DIPARTIMENTO_AGGREGAZIONE_PER_DIPARTIMENTO" ( "ID_DIPARTIMENTO" INTEGER (3) PRIMARY KEY ,"NOME" VARCHAR (20)); 
CREATE TABLE "AGGREGAZIONE_PER_DIPARTIMENTO" ( "ID_DIPARTIMENTO" INTEGER (3) PRIMARY KEY ,"STIPENDIO_LORDO" FLOAT ,"STIPENDIO_NETTO" FLOAT ,"COMPETENZE" FLOAT ); 
CREATE TABLE "AGGREGAZIONE_PER_STIPENDIO_MEDIO_ORARIO" ( "MATRICOLA" INTEGER (3) FOREIGN KEY REFERENCES MATRICOLA_AGGREGAZIONE_PER_STIPENDIO_MEDIO_ORARIO("MATRICOLA"),"ID_ANNO" INTEGER (3) FOREIGN KEY REFERENCES ANNO_AGGREGAZIONE_PER_STIPENDIO_MEDIO_ORARIO("ID_ANNO"),"STIPENDIO_LORDO" FLOAT ,"STIPENDIO_NETTO" FLOAT ,"COMPETENZE" FLOAT ); 
CREATE TABLE "AGGREGAZIONE_PER_STIPENDIO_MEDIO_MENSILE" ( "MATRICOLA" INTEGER (3) FOREIGN KEY REFERENCES MATRICOLA_AGGREGAZIONE_PER_STIPENDIO_MEDIO_MENSILE("MATRICOLA"),"ID_ANNO" INTEGER (3) FOREIGN KEY REFERENCES ANNO_AGGREGAZIONE_PER_STIPENDIO_MEDIO_MENSILE("ID_ANNO"),"STIPENDIO_LORDO" FLOAT ,"STIPENDIO_NETTO" FLOAT ,"COMPETENZE" FLOAT ); 
CREATE TABLE "AGGREGAZIONE_PER_STIPENDIO_ANNUO" ( "MATRICOLA" INTEGER (3) FOREIGN KEY REFERENCES MATRICOLA_AGGREGAZIONE_PER_STIPENDIO_ANNUO("MATRICOLA"),"ID_ANNO" INTEGER (3) FOREIGN KEY REFERENCES ANNO_AGGREGAZIONE_PER_STIPENDIO_ANNUO("ID_ANNO"),"STIPENDIO_LORDO" FLOAT ,"STIPENDIO_NETTO" FLOAT ,"COMPETENZE" FLOAT ); 
CREATE TABLE "AGGREGAZIONE_PER_LIVELLO" ( "ID_LIVELLO" INTEGER (3),"STIPENDIO_LORDO" FLOAT ,"STIPENDIO_NETTO" FLOAT ,"COMPETENZE" FLOAT ); 

